apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wmjwoglmc-nodejs
  janus-idp.io/tekton: wmjwoglmc-nodejs
  backstage.io/kubernetes-id: wmjwoglmc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wmjwoglmc-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
